#!/usr/bin/env python
# coding: utf-8

# In this project we will build a nice web app that allows you to swap out the background of a subject and substitute it with an image generated by Stable Diffusion through a text prompt

# Chong Kiat Lim, chong_kiat.lim@mercedes-benz.com

import os
from dotenv import load_dotenv
load_dotenv()

from PIL import Image
import requests
from transformers import SamModel, SamProcessor
from diffusers import DiffusionPipeline, AutoPipelineForText2Image, AutoPipelineForInpainting
from diffusers.utils import load_image, make_image_grid
from diffusers import StableDiffusionInpaintPipeline
import app

import torch
import numpy as np
import math


# ## SAM
# 
# Complete the following cell by loading the pretrained SAM from Facebook/Meta. Remember to:
# 
# 1. Move the model to the GPU by adding `.to("cuda")`
# 

# Load the SAM model as we have seen in the class
# Remeber to load it on the GPU by adding .to("cuda")
# at the end

sam_pretrained_model = os.getenv("SAM_MODEL_NAME", "facebook/sam-vit-base")
inpainting_model_name = os.getenv("INPAINTING_MODEL_NAME", "runwayml/stable-diffusion-inpainting")
hf_token = os.getenv("HF_TOKEN") or None

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load the SAM model with pre-trained weights 
model = SamModel.from_pretrained(sam_pretrained_model, token=hf_token)

# Move the model to GPU is available
model.to(device=device)

# Load the SamProcessor using the facebook/sam-vit-base checkpoint
processor = SamProcessor.from_pretrained(sam_pretrained_model, token=hf_token)

# Check the device
print(f"Task is running on : {device}")


# Get the mask


def mask_to_rgb(mask):
    """
    Transforms a binary mask into an RGBA image for visualization
    """
    
    bg_transparent = np.zeros(mask.shape + (4, ), dtype=np.uint8)
    
    # Color the area we will replace in green
    # (this vector is [Red, Green, Blue, Alpha])
    bg_transparent[mask == 1] = [0, 255, 0, 127]
    
    return bg_transparent


def get_processed_inputs(image, input_points):
    
    # Use the processor to generate the right inputs
    # for SAM
    # Use "image" as your image
    # Use 'input_points' as your input_points,
    # and remember to use the option return_tensors='pt'
    # Also, remember to add .to("cuda") at the end
    
    # Generate Inputs Using Processor
    inputs = processor(
                        image,
                        input_points=input_points,
                        return_tensors="pt"
                      ).to(device=device)
    
    # Call SAM
    outputs = model(**inputs)
    
    # Now let's post process the outputs of SAM to obtain the masks
    masks = processor.image_processor.post_process_masks(
       outputs.pred_masks.cpu(), 
       inputs["original_sizes"].cpu(), 
       inputs["reshaped_input_sizes"].cpu()
    )
    
    # Here we select the mask with the highest score
    # as the mask we will use. You can experiment with also
    # other selection criteria, for example the largest mask
    # instead of the most confident mask
    best_mask = masks[0][0][outputs.iou_scores.argmax()] 

    # NOTE: we invert the mask by using the ~ operator because
    # so that the subject pixels will have a value of 0 and the
    # background pixels a value of 1. This will make it more convenient
    # to infill the background
    return ~best_mask.cpu().numpy()


# ## Inpainting
# 
# Now that we have completed the SAM setup, let's move to the inpainting setup.
# 
# Let's start by loading our inpainting pipeline. We will use the `diffusers/stable-diffusion-xl-1.0-inpainting-0.1` pretrained model and the `AutoPipelineForInpainting`.
# 
# Complete the following code and run it (it might take a few minutes to run):
# 
# > **NOTE**: you will probably see a warning similar to ``The config attributes {'decay'...``. Please ignore it. It is a warning generated by the diffusers library that does not constitute a problem for our application
# Load the AutoPipelineForInpainting pipeline 
# The checkpoint we want to use is 
# "diffusers/stable-diffusion-xl-1.0-inpainting-0.1"
# Remember to add torch_dtype=torch.float16 as an option

##################
# diffuser_model_name = "diffusers/stable-diffusion-xl-1.0-inpainting-0.1"
# 
# pipeline = AutoPipelineForInpainting.from_pretrained(
#                 diffuser_model_name, 
#                 torch_dtype=torch.float16
#            )
# 
##  This will make it more efficient on our hardware
# pipeline.enable_model_cpu_offload()
####################

if (torch.cuda.is_available()):
    pipeline = StableDiffusionInpaintPipeline.from_pretrained(
                inpainting_model_name,
                torch_dtype=torch.float16,
                use_safetensors=True,
                variant="fp16",
                token=hf_token,
            ).to(device=device)
    
    # This will make it more efficient on our hardware
    pipeline.enable_model_cpu_offload()

else:
    pipeline = StableDiffusionInpaintPipeline.from_pretrained(
                inpainting_model_name,
                use_safetensors=True,
                variant="fp16",
                token=hf_token,
            ).to(device=device)


# Now complete the following function that gets in input:
# 1. The raw image
# 2. The mask generated by SAM (a numpy array)
# 3. The text prompt for the infill
# 4. An optional negative prompt
# 5. An optional seed for repeatibility
# 6. The Classifier-Free Guidance Scale (CFGS).


def make_divisible_by_8(x):
    return int(math.ceil(x / 8.0)) * 8



def inpaint(raw_image, input_mask, prompt, negative_prompt=None, seed=74294536, cfgs=7, num_inference_steps=100, height=None, width=None):

    # Use the pipeline we have created in the previous cell
    # Use "prompt" as prompt, 
    # "negative_prompt" as the negative prompt,
    # raw_image as the image,
    # mask_image as the mask_image,
    # rand_gen as the generator and
    # cfgs as the guidance_scale
    
    original_width, original_height = raw_image.size

    if height is None:
        height = original_height
    if width is None:
        width = original_width

    # Modified height and width
    new_height = make_divisible_by_8(height)
    new_width = make_divisible_by_8(width)

    raw_image = raw_image.resize((new_width, new_height), Image.LANCZOS)  # Or another resampling filter
    mask_image = Image.fromarray(input_mask).resize((new_width, new_height), Image.NEAREST) # Use nearest neighbor for masks

    rand_gen = torch.manual_seed(seed)
    
    image = pipeline(
                        prompt=prompt, 
                        negative_prompt=negative_prompt, 
                        image=raw_image, 
                        mask_image=mask_image, 
                        generator=rand_gen, 
                        guidance_scale=cfgs,
                        num_inference_steps=num_inference_steps,
                        height=new_height, # Pass the divisible height
                        width=new_width  # Pass the divisible width
                     ).images[0]
    
    return image


#def inpaint(raw_image, input_mask, prompt, negative_prompt=None, seed=74294536, cfgs=7, num_inference_steps=100):
#    
#    mask_image = Image.fromarray(input_mask)
#    
#    rand_gen = torch.manual_seed(seed)
#    
#    # Use the pipeline we have created in the previous cell
#    # Use "prompt" as prompt, 
#    # "negative_prompt" as the negative prompt,
#    # raw_image as the image,
#    # mask_image as the mask_image,
#    # rand_gen as the generator and
#    # cfgs as the guidance_scale
#    
#    image = pipeline(
#                        prompt=prompt, 
#                        negative_prompt=negative_prompt, 
#                        image=raw_image, 
#                        mask_image=mask_image, 
#                        generator=rand_gen, 
#                        guidance_scale=cfgs,
#                        num_inference_steps=num_inference_steps
#                     ).images[0]
#    
#    return image


# Interactive app
genai_app = app.generate_app(get_processed_inputs, inpaint)

